# Generated by Django 6.0.1 on 2026-01-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chaye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='Price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
